# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de6533b935c7192df22634eba0ef2b133b294e71985d95ab2707dd2597eae0fea6ac0968f8c7a2345c00ca2942cbeff081c5f417e105a1b7f7c78736a8ebc663

test:
  secret_key_base: a7081e57be59571c1ca768b5ae0eed4e390d65b24277c4905c8592c8cf2a016d31b4e46a0695b4afef0968801b154a5539bba0927e3760cc6bb049a4995e96ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
